name: Discover Prophet Daily Update

on:
  schedule:
    # Esegui ogni giorno alle 02:00 UTC (corrisponde alle 04:00 CEST in estate e 03:00 CET in inverno)
    - cron: '0 2 * * *'
  
  # Permette l'esecuzione manuale dal tab Actions
  workflow_dispatch:

jobs:
  update-trends:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy requests bs4 tqdm cloudscraper fake-useragent
          pip install urllib3==1.26.15
          pip install pytrends==4.9.2
      
      - name: Create required directories
        run: |
          mkdir -p templates
          mkdir -p docs
          mkdir -p checkpoint_data
      
      - name: Copy template files
        run: |
          cp templates/index.html templates/index.html.bak || echo "No previous template to backup"
          cp index.html templates/index.html || echo "Using default template"
          cp style.css templates/style.css || echo "Using default style"
          cp script.js templates/script.js || echo "Using default script"
      
      - name: Run Discover Prophet script
        run: python discover_prophet.py
      
      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Commit and push changes
        run: |
          # Aggiungi tutti i file generati
          git add docs/
          git add checkpoint_data/
          
          # Commit con timestamp
          git commit -m "Update trends data: $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          
          # Push dei cambiamenti
          git push
